"""strip_engagement_flat_columns_rename_format_enum

Revision ID: 2f1a8b9f48c4
Revises: 7fa1aefd781f
Create Date: 2026-06-20 07:48:09.223303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f1a8b9f48c4'
down_revision: Union[str, Sequence[str], None] = '7fa1aefd781f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('engagements_source_id_fkey'), 'engagements', type_='foreignkey')
    op.drop_column('engagements', 'cover_url')
    op.drop_column('engagements', 'source_id')
    op.drop_column('engagements', 'isbn')
    op.drop_column('engagements', 'formats')
    op.drop_column('engagements', 'custom_page_count')
    op.drop_column('engagements', 'custom_audio_minutes')
    op.execute("DROP TYPE reading_format")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagements', sa.Column('custom_audio_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('engagements', sa.Column('custom_page_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('engagements', sa.Column('formats', postgresql.ARRAY(postgresql.ENUM('print', 'digital', 'audio', name='reading_format')), autoincrement=False, nullable=False))
    op.add_column('engagements', sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('engagements', sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('engagements', sa.Column('cover_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('engagements_source_id_fkey'), 'engagements', 'book_sources', ['source_id'], ['id'])
    # ### end Alembic commands ###
