"""add editions and engagement_editions

Revision ID: 7fa1aefd781f
Revises: 9498b92525d8
Create Date: 2026-06-17 21:32:00.365795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa1aefd781f'
down_revision: Union[str, Sequence[str], None] = '9498b92525d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('editions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('edition_format', sa.Enum('print', 'digital', 'audio', name='edition_format'), nullable=False),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_editions_book_format_generic', 'editions', ['book_id', 'edition_format'], unique=True, postgresql_where=sa.text('isbn IS NULL'))
    op.create_table('engagement_editions',
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('edition_id', sa.Uuid(), nullable=False),
    sa.Column('origin_id', sa.Uuid(), nullable=True),
    sa.Column('length_override', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['origin_id'], ['book_sources.id'], ),
    sa.PrimaryKeyConstraint('engagement_id', 'edition_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engagement_editions')
    op.drop_index('ix_editions_book_format_generic', table_name='editions', postgresql_where=sa.text('isbn IS NULL'))
    op.drop_table('editions')
    # ### end Alembic commands ###
