"""add_abandoned_on_to_engagements

Revision ID: cbd9acfdf737
Revises: 2f1a8b9f48c4
Create Date: 2026-06-20 20:36:40.996481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbd9acfdf737'
down_revision: Union[str, Sequence[str], None] = '2f1a8b9f48c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engagements', sa.Column('abandoned_on', sa.Date(), nullable=True))
    op.add_column('engagements', sa.Column('abandoned_on_precision', sa.Enum('day', 'month', 'year', name='date_precision', create_type=False), nullable=False, server_default=sa.text("'day'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('engagements', 'abandoned_on_precision')
    op.drop_column('engagements', 'abandoned_on')
    # ### end Alembic commands ###
