"""create initial tables

Revision ID: feb620ee13b3
Revises: 
Create Date: 2026-06-08 20:34:35.017913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'feb620ee13b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("CREATE TYPE date_precision AS ENUM ('day', 'month', 'year')"))
    op.create_table('authors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('gender_identity', sa.String(), nullable=True),
    sa.Column('bipoc', sa.Boolean(), nullable=False),
    sa.Column('lgbt', sa.Boolean(), nullable=False),
    sa.Column('other_attributes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('google_books_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('written_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('google_books_id', sa.String(), nullable=True),
    sa.Column('default_cover_url', sa.String(), nullable=True),
    sa.Column('default_page_count', sa.Integer(), nullable=True),
    sa.Column('default_audio_minutes', sa.Integer(), nullable=True),
    sa.Column('original_language', sa.String(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('series_position', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('publication_date_precision', sa.Enum('day', 'month', 'year', name='date_precision', metadata=sa.MetaData()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_authors',
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('author', 'illustrator', 'narrator', 'colorist', 'letterer', 'inker', 'editor', name='book_author_role'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id', 'role')
    )
    op.create_table('engagements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('interested', 'tbr', 'reading', 'finished', 'paused', 'dnf', name='reading_status'), nullable=False),
    sa.Column('formats', postgresql.ARRAY(sa.Enum('print', 'digital', 'audio', name='reading_format')), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('cover_url', sa.String(), nullable=True),
    sa.Column('custom_page_count', sa.Integer(), nullable=True),
    sa.Column('custom_audio_minutes', sa.Integer(), nullable=True),
    sa.Column('interested_on', sa.Date(), nullable=True),
    sa.Column('interested_on_precision', sa.Enum('day', 'month', 'year', name='date_precision', metadata=sa.MetaData()), nullable=False),
    sa.Column('tbr_added_on', sa.Date(), nullable=True),
    sa.Column('tbr_added_on_precision', sa.Enum('day', 'month', 'year', name='date_precision', metadata=sa.MetaData()), nullable=False),
    sa.Column('acquired_on', sa.Date(), nullable=True),
    sa.Column('acquired_on_precision', sa.Enum('day', 'month', 'year', name='date_precision', metadata=sa.MetaData()), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=True),
    sa.Column('started_on_precision', sa.Enum('day', 'month', 'year', name='date_precision', metadata=sa.MetaData()), nullable=False),
    sa.Column('finished_on', sa.Date(), nullable=True),
    sa.Column('finished_on_precision', sa.Enum('day', 'month', 'year', name='date_precision', metadata=sa.MetaData()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['book_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standalone_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('manual_title', sa.String(), nullable=True),
    sa.Column('manual_author', sa.String(), nullable=True),
    sa.Column('read_on', sa.Date(), nullable=False),
    sa.Column('read_on_precision', sa.Enum('day', 'month', 'year', name='date_precision', metadata=sa.MetaData()), nullable=False),
    sa.Column('pages_read', sa.Integer(), nullable=True),
    sa.Column('minutes_listened', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('unit', sa.Enum('pages', 'minutes', name='log_unit'), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('minute_start', sa.Integer(), nullable=True),
    sa.Column('minute_end', sa.Integer(), nullable=True),
    sa.Column('new_ground', sa.Boolean(), nullable=False),
    sa.Column('journal_entry', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('engagement_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('written_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('progress_logs')
    op.drop_table('standalone_entries')
    op.drop_table('engagements')
    op.drop_table('book_authors')
    op.drop_table('books')
    op.drop_table('book_sources')
    op.drop_table('blog_posts')
    op.drop_table('authors')
    # ### end Alembic commands ###
